[package]
name = "enumly"
version = "1.1.1"
edition = "2024"
authors = ["Jababa <im@jababa.im>"]
description = "Provides a procedural macro that exposes a compile-time static list of all variants of an enum."
license = "MIT"

[dependencies]
enumly-derive = "1.1.0"
